---

driver:
  name: ec2
  region: eu-west-1
  require_chef_omnibus: false
  instance_type: t2.micro
  associate_public_ip: true

transport:
  # Looks like this is still a issue: https://github.com/test-kitchen/test-kitchen/issues/1035
  max_ssh_sessions: 2

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbose: true
  ansible_verbosity: 2
  requirements_path: requirements.yml

verifier:
  name: inspec

platforms:
  - name: centos-6
    driver:
      block_device_mappings:
        - device_name: /dev/sda1
          ebs:
            volume_type: gp2
            delete_on_termination: true
  - name: centos-7
    driver:
      block_device_mappings:
        - device_name: /dev/sda1
          ebs:
            volume_type: gp2
            delete_on_termination: true
  - name: rocky-8
    driver:
      platform: rhel
      image_search:
        # https://aws.amazon.com/marketplace/pp/prodview-2otariyxb3mqu
        product-code: "cotnnspjrsi38lfn8qo4ibnnm"
      block_device_mappings:
        - device_name: /dev/sda1
          ebs:
            volume_type: gp2
            delete_on_termination: true
    transport:
      username: rocky

suites:
  - name: default
