---

driver:
  name: docker
  use_sudo: false
  privileged: true
  require_chef_omnibus: false
  run_command: /sbin/init
  volume:
    - '/sys/fs/cgroup:/sys/fs/cgroup:ro'

transport:
  # Looks like this is still a issue: https://github.com/test-kitchen/test-kitchen/issues/1035
  max_ssh_sessions: 1

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbose: true
  ansible_verbosity: 2
  role_name: remi

verifier:
  name: inspec

platforms:
  - name: centos-6
    driver_config:
      dockerfile: test/Dockerfile.centos6
  - name: centos-7
    driver_config:
      dockerfile: test/Dockerfile.centos7
      run_command: /usr/lib/systemd/systemd
  - name: centos-8
    driver_config:
      dockerfile: test/Dockerfile.centos8
      run_command: /usr/lib/systemd/systemd

suites:
  - name: default
