---

- block:
    - name: copy repository definition
      template:
        src=centos6/remi.repo.j2
        dest=/etc/yum.repos.d/remi.repo
        backup=yes

    - name: import the GPG key
      template:
        src=centos6/RPM-GPG-KEY-remi
        dest=/etc/pki/rpm-gpg
        backup=yes

  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

- block:
    - name: copy repository definition
      template:
        src=centos6/remi.repo.j2
        dest=/etc/yum.repos.d/remi.repo
        backup=yes

    - name: import the GPG key
      template:
        src=centos6/RPM-GPG-KEY-remi
        dest=/etc/pki/rpm-gpg
        backup=yes

  when: ansible_distribution == 'Amazon'

- block:
    - name: copy repository definition
      template:
        src=centos7/remi.repo.j2
        dest=/etc/yum.repos.d/remi.repo
        backup=yes

    - name: import the GPG key
      template:
        src=centos7/RPM-GPG-KEY-remi
        dest=/etc/pki/rpm-gpg
        backup=yes

  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

